name: RoyalCommands
main: com.royalevolution.royalcommands.RoyalCommands
version: 1.0.0
authors: [einstein8612, ssnd]
<<<<<<< HEAD
softdepend: [Vault]
commands:
  fly:
    aliases: [rfly]
    description: Toggles your ability to fly
    usage: /<command>
  feed:
    aliases: [rfeed, eat]
    description: Feeds you
    usage: /<command>
    
=======
softdepend: [Vault]
>>>>>>> 1cea4c9804b2a806fcdfe39b53e1ee33acb1b328
