name: RoyalCommands
main: com.royalevolution.royalcommands.RoyalCommands
version: 1.0.0
authors: [einstein8612, ssnd]
softdepend: [vault]
commands:
  fly:
    aliases: [rfly]
    description: Toggles your ability to fly
    usage: /<command>